const FORM_BUILDER_QUESTION_CONDITIONS: {
  EQUALS: 'EQUALS',
  GREATER_THAN: 'GREATER_THAN',
  LESS_THAN: 'LESS_THAN'
}

export const FORM_BUILDER_QUESTION_INPUT_TYPES = {
  TEXT: {
    id: 'TEXT',
    conditions: [FORM_BUILDER_QUESTION_CONDITIONS.EQUALS]
  },
  NUMBER: {
    id: 'NUMBER',
    conditions: [
      FORM_BUILDER_QUESTION_CONDITIONS.EQUALS,
      FORM_BUILDER_QUESTION_CONDITIONS.GREATER_THAN,
      FORM_BUILDER_QUESTION_CONDITIONS.LESS_THAN
    ]
  },
  RADIO: {
    id: 'RADIO',
    conditions: [FORM_BUILDER_QUESTION_CONDITIONS.EQUALS]
  }
}